import { StyleSheet } from "react-native";

export default StyleSheet.create({
  container: {
    flex: 1,
    flexDirection: "column",
  },
  audio_container: { marginVertical: 20 },
  _liveBtnView: {
    width: 160,
    height: 40,
    flexDirection: "row",
    alignSelf: "center",
    alignItems: "center",
    justifyContent: "center",
    backgroundColor: "#FF7676",
    borderRadius: 5,
    opacity: 0.8,
  },
  _liveBtnTxt: {
    fontFamily: "BebasNeue_400Regular",
    fontWeight: "500",
    fontSize: 18,
    lineHeight: 18,
    alignItems: "center",
    textTransform: "uppercase",
    marginTop: 5,
  },
  _subTxt: {
    marginHorizontal: 25,
    marginVertical: 20,
    fontWeight: "400",
    fontSize: 18,
    lineHeight: 22,
    color: "#4D5965",
  },
  playIconView: {
    alignSelf: "center",
    justifyContent: "center",
    alignItems: "center",
    marginHorizontal: 25,
  },
  playicon: {
    position: "absolute",
    alignSelf: "center",
    zIndex: 1,
  },
  _imgs1: {
    width: 60,
    height: 60,
    borderRadius: 5,
    marginVertical: 10,
  },
  _rowColumn: {
    flexDirection: "column",
    marginTop: 90,
    marginHorizontal: 10,
  },
  _rowColumn1: {
    flexDirection: "column",
    marginHorizontal: 10,
    // marginVertical: 35,
    marginTop: -55,
  },
  _title: {
    fontFamily: "BebasNeue_400Regular",
    fontWeight: "400",
    fontSize: 20,
    lineHeight: 24,
  },
  circleView: {
    width: 15,
    height: 15,
    backgroundColor: "#0000FF",
    borderRadius: 15 / 2,
    alignSelf: "center",
  },
  line: {
    alignSelf: "center",
    height: "100%",
    width: 3,
    backgroundColor: "black",
  },
  tour_list_graph: {
    flexDirection: "column",
    paddingHorizontal: 5,
  },
  tour_panel: {
    alignSelf: "center",
    flexDirection: "column",
  },
  artiface_tile: { flexDirection: "row", height: 150 },
  _title2: {
    fontFamily: "BebasNeue_400Regular",
    fontWeight: "400",
    fontSize: 18,
    lineHeight: 21,
  },
  _subTitle: {
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 21,
    color: "#77838F",
    marginHorizontal: 5,
  },
  _tourSubtitle: {
    width: 220,
    fontWeight: "400",
    fontSize: 14,
    lineHeight: 18,
    color: "#77838F",
    textAlign: "auto",
  },
});
